### ISSUE TITLE
请问这个怎么安装来着

### ISSUE THREAD

**Issue by lancewu98** [fanyuecheng/Pica#1]
plist里面没找到url 不是很懂xcode

**Comment by fanyuecheng** [comment]
因为是自用，只能用xcode安装，主要我也没有可供其他人安装的证书。下载后，更改bundleid，选择自己的证书，选择设备安装就好了。
没有ios开发的基础知识，还是有一点点难度的吧大概。

**Comment by HAOOFE** [comment]
请问能否打包成ios app呢？本人ios14以越狱，可以自签的。

**Comment by Ahtaler** [comment]
臣附议，XD

**Comment by fanyuecheng** [comment]
> 请问能否打包成ios app呢？本人ios14以越狱，可以自签的。

release 里面已经上传了ipa包

> 臣附议，XD
release 里面已经上传了ipa包

**Comment by laincat** [comment]
新的没编译一下？用 AltStore 就可以装了吧。

**Comment by fanyuecheng** [comment]
抽空我再打个包------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月3日(星期四) 下午5:51
***@***.***&gt;;
***@***.***&gt;;&quot;State ***@***.***&gt;;
主题:&nbsp;Re: [fanyuecheng/Pica] 请问这个怎么安装来着 (#1)
