### ISSUE TITLE
请问观看历史可以从哪里获取？

### ISSUE THREAD

**Issue by laincat** [fanyuecheng/Pica#10]
目前只有看了哪本书的记录，观看到哪一话详情页之类都没记录？

**Comment by fanyuecheng** [comment]
只是本地记录了本子id，具体ep和page没记录。

**Comment by HarryWang29** [comment]
> 只是本地记录了本子id，具体ep和page没记录。

能增加一下page么？有的时候每次看一半需要再找，还挺麻烦的

**Comment by fanyuecheng** [comment]
> 

完善了历史记录，可以续看了
