### ISSUE TITLE
Pica管理組敬啟

### ISSUE THREAD

**Issue by PICAMANGER** [fanyuecheng/Pica#12]
您好，我是PICA管理組，我們最近遇到了非常多的第三方客戶端使用API，以及盜用流量。
這造成了我們在晚高峰流量經常達到峰值。
所以我們在近日展開了對第三方客戶端的排查工作。
我們懇請您理解，PICA作为平台方，每月付出高昂的傳輸成本，用廣告獲得收入維持開銷是正常的行為，IOS用戶因為APPLE平台限制，我們付出了更多的成本來維持。
希望您能封存相關代碼，停止侵犯我們API的行為，我們也在同步向其他github倉庫進行申訴。
非常感謝您的理解，如果需要證明我們PICA開發者的身份，請回復我們，我們會在 工作日 早9：00-晚5點持續跟進，謝謝

**Comment by laincat** [comment]
你做出更换的原版 app 再来说？原版多容易崩溃，体验根本没有。

再说这个项目 用得人，显然没多少，甚至没看见宣传吧？

**Comment by farway00** [comment]
怒赞楼上

**Comment by Wuyou1998** [comment]
原版刷着刷着就崩溃了，iOS企业证书也经常没有，昨晚下不到官方的好不容易找到这个，真吉尔好用啊。
你能做出这样的体验，我可以月付费。建议和这个作者合作，一起把哔咔建设的更好！

**Comment by yangguo88858** [comment]
不要屈服，一个色情的还来搞投诉。
