### ISSUE TITLE
等到祖国统一我再删库~

### ISSUE THREAD

**Issue by fanyuecheng** [fanyuecheng/Pica#13]
![Screenshot_2021-09-21-22-30-31-227_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/34535969/134191183-8c54d058-5cf1-4702-bc0b-40ca25ec092a.jpg)

**Comment by zhongfly** [comment]
不过现在你也打包不了ipa就是了…

**Comment by fanyuecheng** [comment]
我想打包就打包呀，不过这又不是为人民服务的，爱用不用呗

**Comment by zhongfly** [comment]
> 我想打包就打包呀，不过这又不是为人民服务的，爱用不用呗

我又不是反对你的行为，只是根据你在https://github.com/fanyuecheng/Pica/issues/4 说的情况回复一下而已

**Comment by fanyuecheng** [comment]
我也没别的意思。。。
