### ISSUE TITLE
iOS15.2 打不开耽美花园分类，点击后没有本子欸

### ISSUE THREAD

**Issue by AlanDinkle** [fanyuecheng/Pica#19]
如题

**Comment by fanyuecheng** [comment]
我刚试了，是可以的。

**Comment by AlanDinkle** [comment]
> 我刚试了，是可以的。

![image](https://user-images.githubusercontent.com/68946359/148329669-bbb1cbf5-0b31-4306-a4a2-78a26e10e55d.png)
好多分类都不可以，部分可以。我没用外网，就默认设置

**Comment by fanyuecheng** [comment]
我这里不用梯子是不行的，没法复现。
但是既然出现了“没有任何本子”，说明你这是网络请求成功了，只是没有数据，也是神奇。

**Comment by AlanDinkle** [comment]
> 我这里不用梯子是不行的，没法复现。
> 
> 但是既然出现了“没有任何本子”，说明你这是网络请求成功了，只是没有数据，也是神奇。
> 
> 大概你需要个梯子。
嗯嗯好吧谢谢

**Comment by AlanDinkle** [comment]
好吧谢谢～> 我这里不用梯子是不行的，没法复现。
> 
> 但是既然出现了“没有任何本子”，说明你这是网络请求成功了，只是没有数据，也是神奇。
> 
> 大概你需要个梯子。
