### ISSUE TITLE
iPad模式下编译布局混乱

### ISSUE THREAD

**Issue by jwguo321** [fanyuecheng/Pica#2]
你好，目前在使用MacBook m1, XCode 12。iPad模式下编译布局混乱，有考虑更新iPad布局吗

**Comment by fanyuecheng** [comment]
development info 勾选了iPad吗，不勾选我试了是没问题的，勾选的话就不知道了，暂不考虑适配iPad

**Comment by jwguo321** [comment]
> development info 勾选了iPad吗，不勾选我试了是没问题的，勾选的话就不知道了，暂不考虑适配iPad

勾选了， 好的，谢谢
