### ISSUE TITLE
关于安装之前如何打包的问题

### ISSUE THREAD

**Issue by Joson-Z** [fanyuecheng/Pica#21]
我查看了lssues里面的安装教程。
我没用过xcode。
1.现在用的是win10电脑，
2.已经将altstore通过电脑安装到手机，
3.我下载了你提供的源码，问题是我怎么去打包这份源码？用xcode生成ipa格式的文件？
4.我在下载的压缩包中没有看到有ipa后缀的文件，是我遗漏了什么嘛？
请大佬指导我

**Comment by fanyuecheng** [comment]
release里面有ipa文件

**Comment by Joson-Z** [comment]
release在哪里可以看到啊，我找了半天没看见0 0

**Comment by fanyuecheng** [comment]
https://github.com/fanyuecheng/Pica/releases/download/v1.1.3/Pica.ipa

**Comment by fanyuecheng** [comment]
> 

已更新
