### ISSUE TITLE
'YTKNetwork/YTKNetwork.h' file not found 缺啥依赖？

### ISSUE THREAD

**Issue by Z-fly** [fanyuecheng/Pica#23]
![image](https://user-images.githubusercontent.com/10470892/155645492-674efd67-2e5f-4ee6-bd3f-8ad0ee0bae40.png)

**Comment by fanyuecheng** [comment]
按理说下载源码直接运行即可，所有三方依赖都已经在代码里了。
看你截图应该是用真机运行了？先随便选个iPhone模拟器运行一下看看？
真机运行的话，xcode下cmd+，登录一下自己的apple account
![E664FBBE-0F64-486E-867F-6681D1553467](https://user-images.githubusercontent.com/34535969/155646440-15f1780e-a8df-4d1f-b763-4964acaf8a85.png)

**Comment by Z-fly** [comment]
是因为我用Xcode10.3的原因吗？

**Comment by fanyuecheng** [comment]
你这xcode版本确实太低了，项目里选择的ios版本是13，xcode10压根只能支持到ios12吧？
升级一下吧
