### ISSUE TITLE
多p漫画的“下一话”“上一话”按钮颠倒

### ISSUE THREAD

**Issue by lvlvlvboliqiu** [fanyuecheng/Pica#29]
如题，点击下一话会变上一话，上一话会变下一话，估计名字写反了

**Comment by fanyuecheng** [comment]
确实是，不过做的时候就是这样的
因为数据列表有的是顺序有的是逆序
返回的是 9 8 7 6 5 4 3 2 1 当前是5 上一话仅指的左边 下一话指的右边 
确实有歧义 不过不晓得如何表达较好

**Comment by lvlvlvboliqiu** [comment]
要不把上一话下一话改成左箭头符号，右箭头符号
