### ISSUE TITLE
关于怎么安装

### ISSUE THREAD

**Issue by fanyuecheng** [fanyuecheng/Pica#4]
- 开发人员直接下载，xcode选择开发账号，修改bundleid，选择真机运行
- 非开发人员，下载release里面的ipa包后
1. [altstore](https://altstore.io/) 安装，具体查看altstore相关说明
2. 越狱

注：2021-09-18
必须得交了钱的开发者账号或者该开发者账号加入交了钱的开发者团队下，才能打包。
用七天的免费证书是没法打包的，直接改zip为ipa以前可能行，但是现在是不行的。
本项目不再提供ipa包。

**Comment by fanyuecheng** [comment]
另外寻求2级以上账号提供开发测试。
评论和回复评论需2级以上账号，寻好心人员提供一下账号密码以供开发，可发我邮箱。3q。

**Comment by laincat** [comment]
可否提供 altstore 的安装源？

**Comment by fanyuecheng** [comment]
> 可否提供 altstore 的安装源？

不懂你的意思。
你手机上安装好altstore，在my apps 点击左上角+，从iCloud或者手机中选择ipa文件不就能安装了吗？ipa在release里面

**Comment by laincat** [comment]
类似：
https://github.com/tatsuz0u/EhPanda
它是提供了，这样一个连接，用于 直接 在 altstore 能直接安装 app，或者升级更新 app 之用，不需要每次都去"传输"操作。
https://github.com/tatsuz0u/EhPanda-PromotionResources/raw/main/altStore.json

**Comment by laincat** [comment]
https://github.com/XITRIX/iTorrent/issues/161

**Comment by noah978** [comment]
> Similar:
> https://github.com/tatsuz0u/EhPanda
> It is provided, such a connection is used to directly install the app directly in the altstore, or to upgrade and update the app, without the need to "transfer" operation every time.
> https://github.com/tatsuz0u/EhPanda-PromotionResources/raw/main/altStore.json

I got a request from one of my users to add this app to QuarkSources (https://quarksources.github.io) so before I add this application I have a couple questions: How many languages are supported? And may I use the image screenshots in the README?

Note that EhPanda is already on QuarkSources.

中文翻译 :
我的一位用户要求将此应用程序添加到 QuarkSources (https://quarksources.github.io)，因此在添加此应用程序之前，我有几个问题：支持多少种语言？我可以使用自述文件中的图像截图吗？

请注意，EhPan​​da 已经在 QuarkSources 上。

**Comment by laincat** [comment]
另一个安装“工具”：
https://iosgods.com/topic/130167-windowsmacosm1ios-15-introducing-sideloadly-working-cydia-impactor-alternative/

https://armconverter.com/sideloadly/SideloadlySetup.exe
https://armconverter.com/sideloadly/SideloadlySetup64.exe

**Comment by laincat** [comment]
大佬，打包一下么？感激

**Comment by JshengZ** [comment]
尊敬的开发人员，我发现向下滑的时候，内容是重复的

**Comment by YuuNishiki** [comment]
nice app, great work！
