### ISSUE TITLE
请问为什么ios能不翻墙使用，而Android上的不行？

### ISSUE THREAD

**Issue by Smh2001** [fanyuecheng/Pica#7]

**Comment by fanyuecheng** [comment]
翻墙了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月29日(星期二) 晚上8:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[fanyuecheng/Pica] 请问为什么ios能不翻墙使用，而Android上的不行？ (#7)

**Comment by Smh2001** [comment]
> 
> 翻墙了------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年6月29日(星期二) 晚上8:40 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[fanyuecheng/Pica] 请问为什么ios能不翻墙使用，而Android上的不行？ (#7)

OK谢谢，那请问Android上能有类似的不用vpn的方法来使用吗？

**Comment by fanyuecheng** [comment]
不行 因为这是台湾人搞得 服务器不在大陆 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月29日(星期二) 晚上9:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fanyuecheng/Pica] 请问为什么ios能不翻墙使用，而Android上的不行？ (#7)
